# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `hightop` gem.
# Please instead update this file by running `bin/tapioca gem hightop`.


# pkg:gem/hightop#lib/hightop/enumerable.rb:1
module Enumerable
  extend ::ActiveSupport::EnumerableCoreExt::Constants

  # pkg:gem/hightop#lib/hightop/enumerable.rb:2
  def top(*args, **options, &block); end
end

# pkg:gem/hightop#lib/hightop/version.rb:1
module Hightop; end

# pkg:gem/hightop#lib/hightop/kicks.rb:2
module Hightop::Kicks
  # pkg:gem/hightop#lib/hightop/kicks.rb:3
  def top(column, limit = T.unsafe(nil), distinct: T.unsafe(nil), min: T.unsafe(nil), nil: T.unsafe(nil)); end
end

# pkg:gem/hightop#lib/hightop/utils.rb:2
module Hightop::Utils
  class << self
    # resolves eagerly
    #
    # pkg:gem/hightop#lib/hightop/utils.rb:18
    def resolve_column(relation, column); end

    # basic version of Active Record disallow_raw_sql!
    # symbol = column (safe), Arel node = SQL (safe), other = untrusted
    # matches table.column and column
    #
    # pkg:gem/hightop#lib/hightop/utils.rb:7
    def validate_column(column); end
  end
end

# pkg:gem/hightop#lib/hightop/version.rb:2
Hightop::VERSION = T.let(T.unsafe(nil), String)
