# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `operandi` gem.
# Please instead update this file by running `bin/tapioca gem operandi`.


# typed: strict
# frozen_string_literal: true

# RBI signatures for Operandi gem.
# These signatures provide Sorbet type checking without requiring sorbet-runtime as a dependency.

# Base class for all service objects
#
# pkg:gem/operandi#lib/operandi/config.rb:3
module Operandi
  class << self
    # Get the global configuration object.
    #
    # @return [Config] the configuration instance
    #
    # pkg:gem/operandi#lib/operandi/config.rb:23
    def config; end

    # Configure Operandi with a block.
    #
    # @example
    #   Operandi.configure do |config|
    #   config.require_arg_type = true
    #   config.require_output_type = true
    #   config.use_transactions = false
    #   end
    # @return [void]
    # @yield [Config] the configuration object
    #
    # pkg:gem/operandi#lib/operandi/config.rb:16
    def configure; end
  end
end

# Raised when an argument or output value doesn't match the expected type.
#
# pkg:gem/operandi#lib/operandi/exceptions.rb:8
class Operandi::ArgTypeError < ::Operandi::Error; end

# Base class for building service objects with arguments, outputs, and steps.
#
# @example Basic service
#   class CreateUser < Operandi::Base
#   arg :name, type: String
#   arg :email, type: String
#
#   output :user, type: User
#
#   step :create_user
#
#   private
#
#   def create_user
#   self.user = User.create!(name: name, email: email)
#   end
#   end
#
#   result = CreateUser.run(name: "John", email: "john@example.com")
#   result.success? # => true
#   result.user     # => #<User id: 1, name: "John">
#
# pkg:gem/operandi#lib/operandi/base.rb:44
class Operandi::Base
  include ::Operandi::Callbacks
  include ::Operandi::Dsl::ArgumentsDsl
  include ::Operandi::Dsl::OutputsDsl
  include ::Operandi::Dsl::StepsDsl
  include ::Operandi::Concerns::Execution
  include ::Operandi::Concerns::StateManagement
  include ::Operandi::Concerns::ParentService
  extend ::Operandi::CallbackDsl
  extend ::Operandi::Dsl::ArgumentsDsl::ClassMethods
  extend ::Operandi::Dsl::OutputsDsl::ClassMethods
  extend ::Operandi::Dsl::StepsDsl::ClassMethods

  # Initialize a new service instance.
  #
  # @param args [Hash] arguments to pass to the service
  # @param config [Hash] runtime configuration overrides
  # @param parent_service [Base, nil] parent service for nested calls
  # @return [Base] a new instance of Base
  #
  # pkg:gem/operandi#lib/operandi/base.rb:83
  def initialize(args = T.unsafe(nil), config = T.unsafe(nil), parent_service = T.unsafe(nil)); end

  # @return [Collection::Base] collection of argument values
  #
  # pkg:gem/operandi#lib/operandi/base.rb:55
  def arg; end

  # @deprecated Use {#arg} instead
  #
  # pkg:gem/operandi#lib/operandi/base.rb:61
  def arguments; end

  # Execute the service steps.
  #
  # @raise [StandardError] re-raises any exception after running always steps
  # @return [void]
  #
  # pkg:gem/operandi#lib/operandi/base.rb:174
  sig { void }
  def call; end

  # Stop executing remaining steps after the current step completes.
  #
  # @return [Boolean] true
  #
  # pkg:gem/operandi#lib/operandi/base.rb:132
  sig { void }
  def done!; end

  # Check if the service has been stopped.
  #
  # @return [Boolean] true if stop! was called
  #
  # pkg:gem/operandi#lib/operandi/base.rb:140
  sig { returns(T::Boolean) }
  def done?; end

  # @return [Messages] collection of error messages
  #
  # pkg:gem/operandi#lib/operandi/base.rb:73
  # Attributes
  sig { returns(Operandi::Messages) }
  def errors; end

  # Check if the service has any errors.
  #
  # @return [Boolean] true if errors collection is not empty
  #
  # pkg:gem/operandi#lib/operandi/base.rb:115
  sig { returns(T::Boolean) }
  def errors?; end

  # Add an error to the :base key.
  #
  # @param message [String] the error message
  # @return [void]
  #
  # pkg:gem/operandi#lib/operandi/base.rb:155
  sig { params(message: String).void }
  def fail!(message); end

  # Add an error and stop execution immediately, causing transaction rollback.
  # Steps marked with `always: true` will still run after this method is called.
  #
  # @param message [String] the error message
  # @raise [FailExecution] always raises to halt execution and rollback
  # @return [void]
  #
  # pkg:gem/operandi#lib/operandi/base.rb:165
  sig { params(message: String).returns(T.noreturn) }
  def fail_immediately!(message); end

  # Check if the service completed with errors.
  #
  # @return [Boolean] true if any errors were added
  #
  # pkg:gem/operandi#lib/operandi/base.rb:108
  sig { returns(T::Boolean) }
  def failed?; end

  # @return [Collection::Base] collection of output values
  #
  # pkg:gem/operandi#lib/operandi/base.rb:58
  def output; end

  # @deprecated Use {#output} instead
  #
  # pkg:gem/operandi#lib/operandi/base.rb:67
  def outputs; end

  # Stop executing remaining steps after the current step completes.
  #
  # @return [Boolean] true
  #
  # pkg:gem/operandi#lib/operandi/base.rb:129
  sig { void }
  def stop!; end

  # Stop execution immediately, skipping any remaining code in the current step.
  #
  # @raise [StopExecution] always raises to halt execution
  # @return [void]
  #
  # pkg:gem/operandi#lib/operandi/base.rb:146
  sig { returns(T.noreturn) }
  def stop_immediately!; end

  # Check if the service has been stopped.
  #
  # @return [Boolean] true if stop! was called
  #
  # pkg:gem/operandi#lib/operandi/base.rb:137
  sig { returns(T::Boolean) }
  def stopped?; end

  # Check if the service completed without errors.
  #
  # @return [Boolean] true if no errors were added
  #
  # pkg:gem/operandi#lib/operandi/base.rb:100
  # Instance methods
  sig { returns(T::Boolean) }
  def success?; end

  # Check if the service completed without errors.
  #
  # @return [Boolean] true if no errors were added
  #
  # pkg:gem/operandi#lib/operandi/base.rb:103
  sig { returns(T::Boolean) }
  def successful?; end

  # @return [Messages] collection of warning messages
  #
  # pkg:gem/operandi#lib/operandi/base.rb:76
  sig { returns(Operandi::Messages) }
  def warnings; end

  # Check if the service has any warnings.
  #
  # @return [Boolean] true if warnings collection is not empty
  #
  # pkg:gem/operandi#lib/operandi/base.rb:122
  sig { returns(T::Boolean) }
  def warnings?; end

  # Class methods
  class << self
    # @return [Hash, nil] class-level configuration options
    #
    # pkg:gem/operandi#lib/operandi/base.rb:191
    sig { returns(T.nilable(T::Hash[Symbol, T.untyped])) }
    def class_config; end

    # @return [Hash, nil] class-level configuration options
    #
    # pkg:gem/operandi#lib/operandi/base.rb:191
    sig { params(class_config: T.nilable(T::Hash[Symbol, T.untyped])).returns(T.nilable(T::Hash[Symbol, T.untyped])) }
    def class_config=(class_config); end

    # Set class-level configuration for this service.
    #
    # @param config [Hash] configuration options
    # @return [Hash] the configuration hash
    #
    # pkg:gem/operandi#lib/operandi/base.rb:197
    sig { params(config: T::Hash[Symbol, T.untyped]).returns(T::Hash[Symbol, T.untyped]) }
    def config(config = T.unsafe(nil)); end

    # Run the service and return the result.
    #
    # @example
    #   result = MyService.run(name: "test")
    #   result.success? # => true
    # @param kwargs [Hash] keyword arguments matching service arguments
    # @return [Base] the executed service instance
    #
    # pkg:gem/operandi#lib/operandi/base.rb:209
    sig { params(kwargs: T.untyped).returns(T.attached_class) }
    def run(**kwargs); end

    # Run the service and raise an error if it fails.
    #
    # @example
    #   MyService.run!(name: "test") # raises if service fails
    # @param kwargs [Hash] keyword arguments matching service arguments
    # @raise [Error] if the service fails
    # @return [Base] the executed service instance
    #
    # pkg:gem/operandi#lib/operandi/base.rb:221
    sig { params(kwargs: T.untyped).returns(T.attached_class) }
    def run!(**kwargs); end

    # Create a context for running the service with a parent service or config.
    #
    # @example With configuration
    #   MyService.with(use_transactions: false).run(name: "test")
    # @example With parent service
    #   ChildService.with(self).run(data: value)
    # @param config [Hash] configuration hash (when first param is a service)
    # @param service_or_config [Base, Hash] parent service or configuration hash
    # @return [BaseWithContext] context wrapper for running the service
    #
    # pkg:gem/operandi#lib/operandi/base.rb:236
    sig do
      params(
        service_or_config: T.any(Operandi::Base, T::Hash[Symbol, T.untyped]),
        config: T::Hash[Symbol, T.untyped]
      ).returns(Operandi::BaseWithContext)
    end
    def with(service_or_config, config = T.unsafe(nil)); end
  end
end

# Wrapper for running a service with a parent context or custom configuration.
# Created via {Base.with} method.
#
# @example Running with custom configuration
#   MyService.with(use_transactions: false).run(name: "test")
# @example Running with parent service context
#   ChildService.with(self).run(data: value)
#
# pkg:gem/operandi#lib/operandi/base_with_context.rb:12
class Operandi::BaseWithContext
  # Initialize a new context wrapper.
  #
  # @param config [Hash] configuration overrides
  # @param parent_service [Base, nil] parent service for error/warning propagation
  # @param service_class [Class] the service class to run
  # @raise [ArgTypeError] if parent_service is not a Base subclass
  # @return [BaseWithContext] a new instance of BaseWithContext
  #
  # pkg:gem/operandi#lib/operandi/base_with_context.rb:19
  sig do
    params(
      service_class: T.class_of(Operandi::Base),
      parent_service: T.nilable(Operandi::Base),
      config: T::Hash[Symbol, T.untyped]
    ).void
  end
  def initialize(service_class, parent_service, config); end

  # Run the service with the configured context.
  #
  # @param kwargs [Hash] keyword arguments matching service arguments
  # @return [Base] the executed service instance
  #
  # pkg:gem/operandi#lib/operandi/base_with_context.rb:33
  sig { params(kwargs: T.untyped).returns(Operandi::Base) }
  def run(**kwargs); end

  # Run the service and raise an error if it fails.
  #
  # @param kwargs [Hash] keyword arguments matching service arguments
  # @raise [Error] if the service fails
  # @return [Base] the executed service instance
  #
  # pkg:gem/operandi#lib/operandi/base_with_context.rb:42
  sig { params(kwargs: T.untyped).returns(Operandi::Base) }
  def run!(**kwargs); end

  private

  # pkg:gem/operandi#lib/operandi/base_with_context.rb:49
  def extend_arguments(args); end
end

# Class methods for registering callbacks.
# Extend this module in your service class to get callback DSL methods.
#
# @example
#   class MyService < Operandi::Base
#   before_service_run :setup
#   after_service_run :cleanup
#   end
#
# pkg:gem/operandi#lib/operandi/callbacks.rb:106
module Operandi::CallbackDsl
  # Registers a callback to run after the service completes (regardless of success/failure).
  #
  # @example With block
  #   after_service_run { |service| Rails.logger.info("Done!") }
  # @example With method name
  #   after_service_run :cleanup
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield [service] block to execute if no method name provided
  # @yieldparam service [Operandi::Base] the service instance
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:250
  def after_service_run(method_name = T.unsafe(nil), &_arg1); end

  # Registers a callback to run after each step executes.
  #
  # @example With block
  #   after_step_run { |service, step_name| puts "Finished #{step_name}" }
  # @example With method name
  #   after_step_run :log_step_complete
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield [service, step_name] block to execute if no method name provided
  # @yieldparam service [Operandi::Base] the service instance
  # @yieldparam step_name [Symbol] the name of the step that just ran
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:139
  def after_step_run(method_name = T.unsafe(nil), &_arg1); end

  # Get all callbacks for an event including inherited ones.
  #
  # @param event [Symbol] the callback event name
  # @return [Array<Symbol, Proc>] all callbacks for this event
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:322
  def all_callbacks_for(event); end

  # Registers an around callback that wraps the entire service execution.
  # The callback must yield to execute the service.
  #
  # @example With method name
  #   around_service_run :with_timing
  #
  #   def with_timing(service)
  #   start = Time.now
  #   yield
  #   puts "Took #{Time.now - start}s"
  #   end
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield [service] block to execute if no method name provided
  # @yieldparam service [Operandi::Base] the service instance
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:271
  def around_service_run(method_name = T.unsafe(nil), &_arg1); end

  # Registers an around callback that wraps each step execution.
  # The callback must yield to execute the step.
  #
  # @example With method name
  #   around_step_run :with_step_timing
  #
  #   def with_step_timing(service, step_name)
  #   start = Time.now
  #   yield
  #   puts "#{step_name} took #{Time.now - start}s"
  #   end
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield [service, step_name] block to execute if no method name provided
  # @yieldparam service [Operandi::Base] the service instance
  # @yieldparam step_name [Symbol] the name of the step being wrapped
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:161
  def around_step_run(method_name = T.unsafe(nil), &_arg1); end

  # Registers a callback to run before the service starts executing.
  #
  # @example With block
  #   before_service_run { |service| Rails.logger.info("Starting #{service.class.name}") }
  # @example With method name
  #   before_service_run :log_start
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield [service] block to execute if no method name provided
  # @yieldparam service [Operandi::Base] the service instance
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:233
  def before_service_run(method_name = T.unsafe(nil), &_arg1); end

  # Registers a callback to run before each step executes.
  #
  # @example With block
  #   before_step_run { |service, step_name| puts "Starting #{step_name}" }
  # @example With method name
  #   before_step_run :log_step_start
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield [service, step_name] block to execute if no method name provided
  # @yieldparam service [Operandi::Base] the service instance
  # @yieldparam step_name [Symbol] the name of the step about to run
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:121
  def before_step_run(method_name = T.unsafe(nil), &_arg1); end

  # Get callbacks defined in this class for a specific event.
  #
  # @param event [Symbol] the callback event name
  # @return [Array<Symbol, Proc>] callbacks for this event
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:313
  def callbacks_for(event); end

  # Registers a callback to run when the service completes with errors.
  #
  # @example With block
  #   on_service_failure { |service| Rails.logger.error(service.errors.full_messages) }
  # @example With method name
  #   on_service_failure :log_error
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield [service] block to execute if no method name provided
  # @yieldparam service [Operandi::Base] the service instance
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:305
  def on_service_failure(method_name = T.unsafe(nil), &_arg1); end

  # Registers a callback to run when the service completes successfully (without errors).
  #
  # @example With block
  #   on_service_success { |service| NotificationMailer.success(service.user).deliver_later }
  # @example With method name
  #   on_service_success :send_notification
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield [service] block to execute if no method name provided
  # @yieldparam service [Operandi::Base] the service instance
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:288
  def on_service_success(method_name = T.unsafe(nil), &_arg1); end

  # Registers a callback to run when a step raises an exception.
  #
  # @example With block
  #   on_step_crash { |service, step_name, error| Sentry.capture_exception(error) }
  # @example With method name
  #   on_step_crash :report_crash
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield [service, step_name, exception] block to execute if no method name provided
  # @yieldparam exception [Exception] the exception that was raised
  # @yieldparam service [Operandi::Base] the service instance
  # @yieldparam step_name [Symbol] the name of the crashed step
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:216
  def on_step_crash(method_name = T.unsafe(nil), &_arg1); end

  # Registers a callback to run when a step fails (adds errors).
  #
  # @example With block
  #   on_step_failure { |service, step_name| Rails.logger.error("Step #{step_name} failed") }
  # @example With method name
  #   on_step_failure :handle_step_error
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield [service, step_name] block to execute if no method name provided
  # @yieldparam service [Operandi::Base] the service instance
  # @yieldparam step_name [Symbol] the name of the failed step
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:197
  def on_step_failure(method_name = T.unsafe(nil), &_arg1); end

  # Registers a callback to run when a step completes successfully (without adding errors).
  #
  # @example With block
  #   on_step_success { |service, step_name| Analytics.track("step.success", step: step_name) }
  # @example With method name
  #   on_step_success :track_step_success
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield [service, step_name] block to execute if no method name provided
  # @yieldparam service [Operandi::Base] the service instance
  # @yieldparam step_name [Symbol] the name of the successful step
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:179
  def on_step_success(method_name = T.unsafe(nil), &_arg1); end

  private

  # Registers a callback for a given event.
  #
  # @api private
  # @param event [Symbol] the callback event name
  # @param method_name [Symbol, nil] name of the instance method to call
  # @raise [ArgumentError] if neither method name nor block is provided
  # @return [void]
  # @yield block to execute if no method name provided
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:342
  def register_callback(event, method_name = T.unsafe(nil), &block); end
end

# Provides callback hooks for service and step lifecycle events.
#
# @example Around callbacks
#   class MyService < Operandi::Base
#   around_service_run :with_timing
#
#   private
#
#   def with_timing(service)
#   start = Time.now
#   yield
#   puts "Took #{Time.now - start}s"
#   end
#   end
# @example Service-level callbacks
#   class MyService < Operandi::Base
#   before_service_run :log_start
#   after_service_run { |service| Rails.logger.info("Done!") }
#   on_service_success :send_notification
#   on_service_failure :log_error
#   end
# @example Step-level callbacks
#   class MyService < Operandi::Base
#   before_step_run :log_step_start
#   after_step_run { |service, step_name| puts "Finished #{step_name}" }
#   on_step_failure :handle_step_error
#   end
#
# pkg:gem/operandi#lib/operandi/callbacks.rb:33
module Operandi::Callbacks
  # Run all callbacks for a given event.
  #
  # @param args [Array] arguments to pass to callbacks
  # @param event [Symbol] the callback event name
  # @return [void]
  # @yield for around callbacks, the block to wrap
  #
  # pkg:gem/operandi#lib/operandi/callbacks.rb:56
  def run_callbacks(event, *args, &_arg2); end

  private

  # pkg:gem/operandi#lib/operandi/callbacks.rb:86
  def execute_callback(callback, args, &block); end

  # pkg:gem/operandi#lib/operandi/callbacks.rb:75
  def run_around_callbacks(callbacks, args, &block); end

  # pkg:gem/operandi#lib/operandi/callbacks.rb:69
  def run_simple_callbacks(callbacks, args); end
end

# Available callback events.
#
# @return [Array<Symbol>] list of callback event names
#
# pkg:gem/operandi#lib/operandi/callbacks.rb:36
Operandi::Callbacks::EVENTS = T.let(T.unsafe(nil), Array)

# Collection module for storing argument and output values.
#
# pkg:gem/operandi#lib/operandi/collection.rb:7
module Operandi::Collection; end

# Aliases for backwards compatibility
#
# pkg:gem/operandi#lib/operandi/collection.rb:161
Operandi::Collection::Arguments = Operandi::Collection::Base

# Storage for service arguments or outputs with type validation.
#
# @example Accessing values
#   service.arg[:name]     # => "John"
#   service.output[:user]  # => #<User id: 1>
#
# pkg:gem/operandi#lib/operandi/collection.rb:13
class Operandi::Collection::Base
  extend ::Forwardable

  # Initialize a new collection.
  #
  # @param collection_type [String] "arguments" or "outputs"
  # @param instance [Base] the service instance
  # @param storage [Hash] initial values
  # @raise [ArgTypeError] if storage is not a Hash
  # @return [Base] a new instance of Base
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:32
  def initialize(instance, collection_type, storage = T.unsafe(nil)); end

  # Get a value using bracket notation.
  #
  # @param key [Symbol] the key to retrieve
  # @return [Object, nil] the stored value or nil
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:65
  sig { params(key: Symbol).returns(T.untyped) }
  def [](key); end

  # Set a value using bracket notation.
  #
  # @param key [Symbol] the key to set
  # @param value [Object] the value to store
  # @return [Object] the stored value
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:74
  sig { params(key: Symbol, value: T.untyped).returns(T.untyped) }
  def []=(key, value); end

  # Extend arguments hash with context values from this collection.
  # Only applies to arguments collections.
  #
  # @param args [Hash] arguments hash to extend
  # @return [Hash] the extended arguments hash
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:113
  sig { params(args: T::Hash[Symbol, T.untyped]).returns(T::Hash[Symbol, T.untyped]) }
  def extend_with_context(args); end

  # Get a value from the collection.
  #
  # @param key [Symbol] the key to retrieve
  # @return [Object, nil] the stored value or nil
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:57
  sig { params(key: Symbol).returns(T.untyped) }
  def get(key); end

  # Check if a key exists in the collection.
  #
  # @param key [Symbol] the key to check
  # @return [Boolean] true if key exists
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:24
  def key?(*_arg0, **_arg1, &_arg2); end

  # Load default values for fields that haven't been set.
  #
  # @return [void]
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:81
  sig { void }
  def load_defaults; end

  # Access a value using method call syntax.
  #
  # @param args [Array] method arguments (must be empty)
  # @param method_name [Symbol] the method name (used as key)
  # @raise [NoMethodError] if the key doesn't exist
  # @return [Object, nil] the stored value or nil
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:131
  def method_missing(method_name, *args, &_arg2); end

  # Set a value in the collection.
  #
  # @param key [Symbol] the key to set
  # @param value [Object] the value to store
  # @return [Object] the stored value
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:49
  sig { params(key: Symbol, value: T.untyped).returns(T.untyped) }
  def set(key, value); end

  # Convert collection to a hash.
  #
  # @return [Hash] the stored values
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:24
  def to_h(*_arg0, **_arg1, &_arg2); end

  # Validate all values against their type definitions.
  #
  # @raise [ArgTypeError] if a value fails type validation
  # @return [void]
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:97
  sig { void }
  def validate!; end

  private

  # Check if a method name corresponds to a stored key.
  #
  # @param include_private [Boolean] whether to include private methods
  # @param method_name [Symbol] the method name to check
  # @return [Boolean] true if the key exists
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:142
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end

  # pkg:gem/operandi#lib/operandi/collection.rb:155
  def settings_collection; end

  # @raise [ArgumentError]
  #
  # pkg:gem/operandi#lib/operandi/collection.rb:148
  def validate_collection_type!(type); end
end

# pkg:gem/operandi#lib/operandi/collection.rb:162
Operandi::Collection::Outputs = Operandi::Collection::Base

# Collection type constants
#
# pkg:gem/operandi#lib/operandi/constants.rb:5
module Operandi::CollectionTypes; end

# pkg:gem/operandi#lib/operandi/constants.rb:9
Operandi::CollectionTypes::ALL = T.let(T.unsafe(nil), Array)

# pkg:gem/operandi#lib/operandi/constants.rb:6
Operandi::CollectionTypes::ARGUMENTS = T.let(T.unsafe(nil), Symbol)

# pkg:gem/operandi#lib/operandi/constants.rb:7
Operandi::CollectionTypes::OUTPUTS = T.let(T.unsafe(nil), Symbol)

# pkg:gem/operandi#lib/operandi/concerns/execution.rb:4
module Operandi::Concerns; end

# Handles service execution logic including steps and validation
#
# pkg:gem/operandi#lib/operandi/concerns/execution.rb:6
module Operandi::Concerns::Execution
  private

  # Execute the main service logic
  #
  # pkg:gem/operandi#lib/operandi/concerns/execution.rb:10
  def execute_service; end

  # Load defaults for outputs and arguments, then validate arguments
  #
  # pkg:gem/operandi#lib/operandi/concerns/execution.rb:64
  def load_defaults_and_validate; end

  # Run all service result callbacks based on success/failure
  #
  # pkg:gem/operandi#lib/operandi/concerns/execution.rb:21
  def run_service_result_callbacks; end

  # Run normal steps within transaction
  #
  # pkg:gem/operandi#lib/operandi/concerns/execution.rb:32
  def run_steps; end

  # Run steps with parameter `always` if they weren't launched because of errors/warnings
  #
  # pkg:gem/operandi#lib/operandi/concerns/execution.rb:52
  def run_steps_with_always; end

  # Execute block within transaction if configured
  #
  # pkg:gem/operandi#lib/operandi/concerns/execution.rb:71
  def within_transaction(&_arg0); end
end

# Handles copying errors and warnings to parent services
#
# pkg:gem/operandi#lib/operandi/concerns/parent_service.rb:6
module Operandi::Concerns::ParentService
  private

  # Copy errors from this service to parent service
  #
  # pkg:gem/operandi#lib/operandi/concerns/parent_service.rb:21
  def copy_errors_to_parent_service; end

  # Copy warnings from this service to parent service
  #
  # pkg:gem/operandi#lib/operandi/concerns/parent_service.rb:10
  def copy_warnings_to_parent_service; end
end

# Manages service state including errors and warnings initialization
#
# pkg:gem/operandi#lib/operandi/concerns/state_management.rb:6
module Operandi::Concerns::StateManagement
  private

  # Initialize errors collection with configuration
  #
  # pkg:gem/operandi#lib/operandi/concerns/state_management.rb:10
  def initialize_errors; end

  # Initialize warnings collection with configuration
  #
  # pkg:gem/operandi#lib/operandi/concerns/state_management.rb:19
  def initialize_warnings; end
end

# Configuration class for Operandi global settings.
#
# @example Accessing configuration
#   Operandi.config.require_arg_type # => true
# @example Modifying configuration
#   Operandi.config.use_transactions = false
#
# pkg:gem/operandi#lib/operandi/config.rb:35
class Operandi::Config
  # Initialize configuration with default values.
  #
  # @return [Config] a new instance of Config
  #
  # pkg:gem/operandi#lib/operandi/config.rb:110
  def initialize; end

  # @return [Boolean] whether to stop executing steps when an error is added
  #
  # pkg:gem/operandi#lib/operandi/config.rb:49
  def break_on_error; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def break_on_error=(value); end

  # @return [Boolean] whether to stop executing steps when a warning is added
  #
  # pkg:gem/operandi#lib/operandi/config.rb:61
  def break_on_warning; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def break_on_warning=(value); end

  # @return [Boolean] whether to copy errors to parent service in chain
  #
  # pkg:gem/operandi#lib/operandi/config.rb:46
  def load_errors; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def load_errors=(value); end

  # @return [Boolean] whether to copy warnings to parent service in chain
  #
  # pkg:gem/operandi#lib/operandi/config.rb:58
  def load_warnings; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def load_warnings=(value); end

  # Merge configuration with additional options.
  #
  # @param config [Hash] options to merge
  # @return [Hash] merged configuration hash
  #
  # pkg:gem/operandi#lib/operandi/config.rb:138
  def merge(config); end

  # @return [Boolean] whether to raise Operandi::Error when service fails
  #
  # pkg:gem/operandi#lib/operandi/config.rb:52
  def raise_on_error; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def raise_on_error=(value); end

  # @return [Boolean] whether to raise Operandi::Error when service has warnings
  #
  # pkg:gem/operandi#lib/operandi/config.rb:64
  def raise_on_warning; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def raise_on_warning=(value); end

  # @return [Boolean] whether arguments must have a type specified
  #
  # pkg:gem/operandi#lib/operandi/config.rb:37
  def require_arg_type; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def require_arg_type=(value); end

  # @return [Boolean] whether outputs must have a type specified
  #
  # pkg:gem/operandi#lib/operandi/config.rb:40
  def require_output_type; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def require_output_type=(value); end

  # Convenience setter for backward compatibility.
  # Sets both require_arg_type and require_output_type.
  #
  # @param value [Boolean] whether to require types for arguments and outputs
  # @return [void]
  #
  # pkg:gem/operandi#lib/operandi/config.rb:104
  def require_type=(value); end

  # Reset all configuration options to their default values.
  #
  # @return [void]
  #
  # pkg:gem/operandi#lib/operandi/config.rb:117
  def reset_to_defaults!; end

  # @return [Boolean] whether to rollback the transaction when an error is added
  #
  # pkg:gem/operandi#lib/operandi/config.rb:55
  def rollback_on_error; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def rollback_on_error=(value); end

  # @return [Boolean] whether to rollback the transaction when a warning is added
  #
  # pkg:gem/operandi#lib/operandi/config.rb:67
  def rollback_on_warning; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def rollback_on_warning=(value); end

  # @return [Hash{String => String}] custom type mappings for Ruby LSP addon.
  #   Maps custom types to Ruby types for hover/completion.
  #   @example { "CustomTypes::UUID" => "String", "CustomTypes::Money" => "BigDecimal" }
  #
  # pkg:gem/operandi#lib/operandi/config.rb:72
  def ruby_lsp_type_mappings; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def ruby_lsp_type_mappings=(value); end

  # Convert configuration to a hash.
  #
  # @return [Hash{Symbol => Object}] all configuration options as a hash
  #
  # pkg:gem/operandi#lib/operandi/config.rb:128
  def to_h; end

  # @return [Boolean] whether to wrap service execution in a database transaction
  #
  # pkg:gem/operandi#lib/operandi/config.rb:43
  def use_transactions; end

  # pkg:gem/operandi#lib/operandi/config.rb:93
  def use_transactions=(value); end
end

# pkg:gem/operandi#lib/operandi/config.rb:74
Operandi::Config::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/operandi#lib/operandi/dsl/validation.rb:6
module Operandi::Dsl; end

# DSL for defining and managing service arguments
#
# pkg:gem/operandi#lib/operandi/dsl/arguments_dsl.rb:9
module Operandi::Dsl::ArgumentsDsl
  mixes_in_class_methods ::Operandi::Dsl::ArgumentsDsl::ClassMethods

  class << self
    # @private
    #
    # pkg:gem/operandi#lib/operandi/dsl/arguments_dsl.rb:10
    def included(base); end
  end
end

# pkg:gem/operandi#lib/operandi/dsl/arguments_dsl.rb:14
module Operandi::Dsl::ArgumentsDsl::ClassMethods
  # Define an argument for the service
  #
  # @example Define a context argument passed to child services
  #   arg :current_user, type: User, context: true
  # @example Define a required string argument
  #   arg :name, type: String
  # @example Define an argument with multiple allowed types
  #   arg :id, type: [String, Integer]
  # @example Define an argument with proc default
  #   arg :timestamp, type: Time, default: -> { Time.now }
  # @example Define an optional argument with default
  #   arg :age, type: Integer, optional: true, default: 25
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @param name [Symbol] the argument name
  # @param opts [Hash] options for configuring the argument
  #
  # pkg:gem/operandi#lib/operandi/dsl/arguments_dsl.rb:39
  def arg(name, opts = T.unsafe(nil)); end

  # Get all arguments including inherited ones
  #
  # @return [Hash] all arguments defined for this service
  #
  # pkg:gem/operandi#lib/operandi/dsl/arguments_dsl.rb:60
  def arguments; end

  # Get only arguments defined in this class
  #
  # @return [Hash] arguments defined in this class only
  #
  # pkg:gem/operandi#lib/operandi/dsl/arguments_dsl.rb:67
  def own_arguments; end

  # Remove an argument from the service
  #
  # @param name [Symbol] the argument name to remove
  #
  # pkg:gem/operandi#lib/operandi/dsl/arguments_dsl.rb:52
  def remove_arg(name); end

  private

  # Build arguments by merging inherited arguments with own arguments
  #
  # @return [Hash] merged arguments
  #
  # pkg:gem/operandi#lib/operandi/dsl/arguments_dsl.rb:76
  def build_arguments; end
end

# DSL for defining and managing service outputs
#
# pkg:gem/operandi#lib/operandi/dsl/outputs_dsl.rb:9
module Operandi::Dsl::OutputsDsl
  mixes_in_class_methods ::Operandi::Dsl::OutputsDsl::ClassMethods

  class << self
    # @private
    #
    # pkg:gem/operandi#lib/operandi/dsl/outputs_dsl.rb:10
    def included(base); end
  end
end

# pkg:gem/operandi#lib/operandi/dsl/outputs_dsl.rb:14
module Operandi::Dsl::OutputsDsl::ClassMethods
  # Define an output for the service
  #
  # @example Define a required hash output
  #   output :result, type: Hash
  # @example Define an optional output with default
  #   output :status, type: String, optional: true, default: "pending"
  # @example Define an output with multiple allowed types
  #   output :data, type: [Hash, Array]
  # @example Define an output with proc default
  #   output :metadata, type: Hash, default: -> { {} }
  # @option opts
  # @option opts
  # @option opts
  # @param name [Symbol] the output name
  # @param opts [Hash] options for configuring the output
  #
  # pkg:gem/operandi#lib/operandi/dsl/outputs_dsl.rb:35
  def output(name, opts = T.unsafe(nil)); end

  # Get all outputs including inherited ones
  #
  # @return [Hash] all outputs defined for this service
  #
  # pkg:gem/operandi#lib/operandi/dsl/outputs_dsl.rb:56
  def outputs; end

  # Get only outputs defined in this class
  #
  # @return [Hash] outputs defined in this class only
  #
  # pkg:gem/operandi#lib/operandi/dsl/outputs_dsl.rb:63
  def own_outputs; end

  # Remove an output from the service
  #
  # @param name [Symbol] the output name to remove
  #
  # pkg:gem/operandi#lib/operandi/dsl/outputs_dsl.rb:48
  def remove_output(name); end

  private

  # Build outputs by merging inherited outputs with own outputs
  #
  # @return [Hash] merged outputs
  #
  # pkg:gem/operandi#lib/operandi/dsl/outputs_dsl.rb:72
  def build_outputs; end
end

# DSL for defining and managing service steps
#
# pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:9
module Operandi::Dsl::StepsDsl
  mixes_in_class_methods ::Operandi::Dsl::StepsDsl::ClassMethods

  class << self
    # @private
    #
    # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:10
    def included(base); end
  end
end

# pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:14
module Operandi::Dsl::StepsDsl::ClassMethods
  # Remove a step from the service
  #
  # @param name [Symbol] the step name to remove
  #
  # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:79
  def remove_step(name); end

  # Define a step for the service
  #
  # @example Define a conditional step
  #   step :send_notification, if: :should_notify?
  #   step :skip_validation, unless: :production?
  # @example Define a simple step
  #   step :validate_input
  # @example Define a step that always runs
  #   step :cleanup, always: true
  # @example Define a step with proc condition
  #   step :premium_feature, if: -> { user.premium? && feature_enabled? }
  # @example Define step ordering
  #   step :log_start, before: :validate_input
  #   step :log_end, after: :process_data
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @param name [Symbol] the step name (must correspond to a private method)
  # @param opts [Hash] options for configuring the step
  #
  # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:41
  def step(name, opts = T.unsafe(nil)); end

  # Get the list of step operations to be applied
  #
  # @return [Array] list of operations
  #
  # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:96
  def step_operations; end

  # Get all steps including inherited ones
  #
  # @return [Hash] all steps defined for this service
  #
  # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:89
  def steps; end

  # Validate that the service has steps defined
  # Called before executing the service
  #
  # @raise [NoStepsError] if no steps are defined
  #
  # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:104
  def validate_steps!; end

  private

  # Apply a single step operation to the steps hash
  #
  # @param operation [Hash] the operation to apply
  # @param steps [Hash] the steps hash
  #
  # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:168
  def apply_step_operation(steps, operation); end

  # Build steps by applying operations to inherited steps
  #
  # @return [Hash] the final steps hash
  #
  # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:127
  def build_steps; end

  # Inherit steps from parent class
  #
  # @return [Hash] inherited steps
  #
  # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:160
  def inherit_steps; end

  # Insert a step before or after a target step
  #
  # @param operation [Hash] the insert operation details
  # @param steps [Hash] the steps hash
  #
  # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:183
  def insert_step(steps, operation); end

  # Check if an instance method is defined in this class or its ancestors
  # (excluding Operandi::Base and its modules)
  #
  # @param method_name [Symbol] the method name to check
  # @return [Boolean] true if the method is defined
  #
  # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:145
  def instance_method_defined?(method_name); end

  # Validate step options to ensure they are valid
  #
  # @param name [Symbol] the step name
  # @param opts [Hash] the step options
  # @raise [Operandi::Error]
  #
  # pkg:gem/operandi#lib/operandi/dsl/steps_dsl.rb:117
  def validate_step_opts!(name, opts); end
end

# Shared validation logic for DSL modules
#
# pkg:gem/operandi#lib/operandi/dsl/validation.rb:8
module Operandi::Dsl::Validation
  class << self
    # Check if a name is already defined as an argument
    #
    # @return [Boolean]
    #
    # pkg:gem/operandi#lib/operandi/dsl/validation.rb:105
    def has_argument?(name_sym, service_class); end

    # Check if a name is already defined as an output
    #
    # @return [Boolean]
    #
    # pkg:gem/operandi#lib/operandi/dsl/validation.rb:113
    def has_output?(name_sym, service_class); end

    # Check if a name is already defined as a step
    #
    # @return [Boolean]
    #
    # pkg:gem/operandi#lib/operandi/dsl/validation.rb:121
    def has_step?(name_sym, service_class); end

    # Check if require_type is enabled for the given field type and service class
    #
    # @param field_type [Symbol] the type of field (:argument, :output)
    # @param service_class [Class] the service class to check
    # @return [Boolean] whether type is required for the field type
    #
    # pkg:gem/operandi#lib/operandi/dsl/validation.rb:150
    def require_type_enabled_for?(field_type, service_class); end

    # Validate argument name doesn't conflict with outputs or steps
    #
    # pkg:gem/operandi#lib/operandi/dsl/validation.rb:54
    def validate_argument_conflicts!(name_sym, service_class); end

    # Validate that the name doesn't conflict with other defined names
    #
    # @param field_type [Symbol] the type of field being defined (:argument, :output, :step)
    # @param name [Symbol] the name to validate
    # @param service_class [Class] the service class to check for conflicts
    #
    # pkg:gem/operandi#lib/operandi/dsl/validation.rb:40
    def validate_name_conflicts!(name, field_type, service_class); end

    # Validate output name doesn't conflict with arguments or steps
    #
    # pkg:gem/operandi#lib/operandi/dsl/validation.rb:71
    def validate_output_conflicts!(name_sym, service_class); end

    # Validate that the name is not a reserved word
    #
    # @param field_type [Symbol] the type of field (:argument, :output, :step)
    # @param name [Symbol] the name to validate
    # @param service_class [Class] the service class for error messages
    # @raise [Operandi::ReservedNameError]
    #
    # pkg:gem/operandi#lib/operandi/dsl/validation.rb:27
    def validate_reserved_name!(name, field_type, service_class); end

    # Validate step name doesn't conflict with arguments or outputs
    #
    # pkg:gem/operandi#lib/operandi/dsl/validation.rb:88
    def validate_step_conflicts!(name_sym, service_class); end

    # Validate that the name is a symbol
    #
    # @param field_type [Symbol] the type of field (:argument, :output, :step)
    # @param name [Object] the name to validate
    # @param service_class [Class] the service class for error messages
    # @raise [Operandi::InvalidNameError]
    #
    # pkg:gem/operandi#lib/operandi/dsl/validation.rb:14
    def validate_symbol_name!(name, field_type, service_class); end

    # Validate that the type option is provided when require_type is enabled
    #
    # @param field_type [Symbol] the type of field (:argument, :output)
    # @param name [Symbol] the field name
    # @param opts [Hash] the options hash to check for type
    # @param service_class [Class] the service class for error messages
    # @raise [Operandi::MissingTypeError]
    #
    # pkg:gem/operandi#lib/operandi/dsl/validation.rb:135
    def validate_type_required!(name, field_type, service_class, opts); end
  end
end

# Base exception class for all Operandi errors.
#
# pkg:gem/operandi#lib/operandi/exceptions.rb:5
class Operandi::Error < ::StandardError; end

# Control flow exception for fail_immediately!
# Unlike StopExecution, this exception causes transaction rollback.
#
# pkg:gem/operandi#lib/operandi/exceptions.rb:28
class Operandi::FailExecution < ::StandardError; end

# Field type constants
#
# pkg:gem/operandi#lib/operandi/constants.rb:13
module Operandi::FieldTypes; end

# pkg:gem/operandi#lib/operandi/constants.rb:17
Operandi::FieldTypes::ALL = T.let(T.unsafe(nil), Array)

# pkg:gem/operandi#lib/operandi/constants.rb:14
Operandi::FieldTypes::ARGUMENT = T.let(T.unsafe(nil), Symbol)

# pkg:gem/operandi#lib/operandi/constants.rb:15
Operandi::FieldTypes::OUTPUT = T.let(T.unsafe(nil), Symbol)

# Raised when a name is invalid (e.g., not a Symbol).
#
# pkg:gem/operandi#lib/operandi/exceptions.rb:14
class Operandi::InvalidNameError < ::Operandi::Error; end

# Represents a single error or warning message.
#
# @example Creating a message
#   message = Message.new(:name, "can't be blank", break: true)
#   message.key    # => :name
#   message.text   # => "can't be blank"
#   message.break? # => true
#
# pkg:gem/operandi#lib/operandi/message.rb:11
class Operandi::Message
  # Create a new message.
  #
  # @option opts
  # @option opts
  # @param key [Symbol] the key/field this message belongs to
  # @param opts [Hash] additional options
  # @param text [String] the message text
  # @return [Message] a new instance of Message
  #
  # pkg:gem/operandi#lib/operandi/message.rb:25
  def initialize(key, text, opts = T.unsafe(nil)); end

  # Check if this message should stop step execution.
  #
  # @return [Boolean] true if break option was set
  #
  # pkg:gem/operandi#lib/operandi/message.rb:34
  def break?; end

  # @return [Symbol] the key/field this message belongs to
  #
  # pkg:gem/operandi#lib/operandi/message.rb:13
  def key; end

  # Check if this message should trigger a transaction rollback.
  #
  # @return [Boolean] true if rollback option was set
  #
  # pkg:gem/operandi#lib/operandi/message.rb:41
  def rollback?; end

  # @return [String] the message text
  #
  # pkg:gem/operandi#lib/operandi/message.rb:16
  def text; end

  # Return the message text.
  #
  # @return [String] the message text
  #
  # pkg:gem/operandi#lib/operandi/message.rb:48
  def to_s; end
end

# Collection of error or warning messages, organized by key.
#
# @example Adding and accessing errors
#   errors.add(:name, "can't be blank")
#   errors.add(:email, "is invalid")
#   errors[:name]  # => [#<Message key: :name, text: "can't be blank">]
#   errors.to_h    # => { name: ["can't be blank"], email: ["is invalid"] }
#
# pkg:gem/operandi#lib/operandi/messages.rb:11
class Operandi::Messages
  extend ::Forwardable

  # Initialize a new messages collection.
  #
  # @option config
  # @option config
  # @option config
  # @param config [Hash] configuration options
  # @return [Messages] a new instance of Messages
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:58
  sig { params(config: T::Hash[Symbol, T.untyped]).void }
  def initialize(config); end

  # Get messages for a specific key.
  #
  # @param key [Symbol] the key to look up
  # @return [Array<Message>, nil] array of messages or nil
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:39
  def [](*_arg0, **_arg1, &_arg2); end

  # Add a message to the collection.
  #
  # @example Add a single error
  #   errors.add(:name, "can't be blank")
  # @example Add multiple errors
  #   errors.add(:email, ["is invalid", "is already taken"])
  # @option opts
  # @option opts
  # @param key [Symbol] the key/field for this message
  # @param opts [Hash] additional options
  # @param texts [String, Array<String>, Message] the message text(s) to add
  # @raise [Error] if text is nil or empty
  # @return [void]
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:86
  sig do
    params(
      key: Symbol,
      texts: T.any(String, T::Array[String], Operandi::Message),
      opts: T::Hash[Symbol, T.untyped]
    ).void
  end
  def add(key, texts, opts = T.unsafe(nil)); end

  # Check if there are any messages.
  #
  # @return [Boolean] true if messages exist
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:39
  def any?(*_arg0, **_arg1, &_arg2); end

  # Check if step execution should stop.
  #
  # @return [Boolean] true if a message triggered a break
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:108
  sig { returns(T::Boolean) }
  def break?; end

  # Copy messages from another source.
  #
  # @example Copy from ActiveRecord model
  #   errors.copy_from(user) # copies user.errors
  # @example Copy from another service
  #   errors.copy_from(child_service)
  # @param entity [ActiveRecord::Base, Base, Hash, #each] source to copy from
  # @param opts [Hash] options to pass to each added message
  # @raise [Error] if entity type is not supported
  # @return [void]
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:124
  sig { params(entity: T.untyped, opts: T::Hash[Symbol, T.untyped]).void }
  def copy_from(entity, opts = T.unsafe(nil)); end

  # Get total count of all messages across all keys.
  #
  # @return [Integer] total number of messages
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:67
  sig { returns(Integer) }
  def count; end

  # pkg:gem/operandi#lib/operandi/messages.rb:39
  def each(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/operandi#lib/operandi/messages.rb:39
  def each_with_index(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/operandi#lib/operandi/messages.rb:39
  def each_with_object(*_arg0, **_arg1, &_arg2); end

  # Check if the collection is empty.
  #
  # @return [Boolean] true if no messages
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:39
  def empty?(*_arg0, **_arg1, &_arg2); end

  # Copy messages from another source.
  #
  # @example Copy from ActiveRecord model
  #   errors.copy_from(user) # copies user.errors
  # @example Copy from another service
  #   errors.copy_from(child_service)
  # @param entity [ActiveRecord::Base, Base, Hash, #each] source to copy from
  # @param opts [Hash] options to pass to each added message
  # @raise [Error] if entity type is not supported
  # @return [void]
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:139
  sig { params(entity: T.untyped, opts: T::Hash[Symbol, T.untyped]).void }
  def from_record(entity, opts = T.unsafe(nil)); end

  # Check if a key has messages.
  #
  # @param key [Symbol] the key to check
  # @return [Boolean] true if key has messages
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:50
  def has_key?(*_arg0, **_arg1, &_arg2); end

  # Check if a key has messages.
  #
  # @param key [Symbol] the key to check
  # @return [Boolean] true if key has messages
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:39
  def key?(*_arg0, **_arg1, &_arg2); end

  # Get all keys with messages.
  #
  # @return [Array<Symbol>] array of keys
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:39
  def keys(*_arg0, **_arg1, &_arg2); end

  # Get number of keys with messages.
  #
  # @return [Integer] number of keys
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:39
  def size(*_arg0, **_arg1, &_arg2); end

  # Convert messages to a hash with string values.
  #
  # @return [Hash{Symbol => Array<String>}] messages as hash
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:144
  sig { returns(T::Hash[Symbol, T::Array[String]]) }
  def to_h; end

  # pkg:gem/operandi#lib/operandi/messages.rb:39
  def values(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/operandi#lib/operandi/messages.rb:156
  def break!(break_execution); end

  # pkg:gem/operandi#lib/operandi/messages.rb:162
  def raise!(message); end

  # @raise [ActiveRecord::Rollback]
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:172
  def rollback!(rollback); end

  # @return [Boolean]
  #
  # pkg:gem/operandi#lib/operandi/messages.rb:150
  def valid_error_text?(text); end
end

# Raised when type is required but not specified for an argument or output.
#
# pkg:gem/operandi#lib/operandi/exceptions.rb:20
class Operandi::MissingTypeError < ::Operandi::Error; end

# @deprecated Use {Error} instead
#
# pkg:gem/operandi#lib/operandi/exceptions.rb:31
Operandi::NoStepError = Operandi::Error

# Raised when a service has no steps defined and no run method.
#
# pkg:gem/operandi#lib/operandi/exceptions.rb:17
class Operandi::NoStepsError < ::Operandi::Error; end

# Raised when using a reserved name for an argument, output, or step.
#
# pkg:gem/operandi#lib/operandi/exceptions.rb:11
class Operandi::ReservedNameError < ::Operandi::Error; end

# Reserved names that cannot be used for arguments, outputs, or steps
# These names would conflict with existing gem methods
#
# pkg:gem/operandi#lib/operandi/constants.rb:22
module Operandi::ReservedNames; end

# All reserved names combined (used for validation)
#
# pkg:gem/operandi#lib/operandi/constants.rb:98
Operandi::ReservedNames::ALL = T.let(T.unsafe(nil), Array)

# Instance methods from Base class and concerns
#
# pkg:gem/operandi#lib/operandi/constants.rb:24
Operandi::ReservedNames::BASE_METHODS = T.let(T.unsafe(nil), Array)

# Callback method names
#
# pkg:gem/operandi#lib/operandi/constants.rb:62
Operandi::ReservedNames::CALLBACK_METHODS = T.let(T.unsafe(nil), Array)

# Class methods that could conflict
#
# pkg:gem/operandi#lib/operandi/constants.rb:45
Operandi::ReservedNames::CLASS_METHODS = T.let(T.unsafe(nil), Array)

# Ruby reserved words and common Object methods
#
# pkg:gem/operandi#lib/operandi/constants.rb:77
Operandi::ReservedNames::RUBY_RESERVED = T.let(T.unsafe(nil), Array)

# pkg:gem/operandi#lib/operandi/settings/step.rb:4
module Operandi::Settings; end

# Aliases for backwards compatibility
#
# pkg:gem/operandi#lib/operandi/settings/field.rb:129
Operandi::Settings::Argument = Operandi::Settings::Field

# Stores configuration for a single argument or output field.
# Created automatically when using the `arg` or `output` DSL methods.
#
# pkg:gem/operandi#lib/operandi/settings/field.rb:7
class Operandi::Settings::Field
  # Initialize a new field definition.
  #
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @option opts
  # @param name [Symbol] the field name
  # @param opts [Hash] field options
  # @param service_class [Class] the service class this field belongs to
  # @return [Field] a new instance of Field
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:33
  def initialize(name, service_class, opts = T.unsafe(nil)); end

  # @return [Boolean, nil] true if this is a context argument
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:18
  def context; end

  # @return [Object, Proc, nil] the default value or proc
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:15
  def default; end

  # @return [Boolean] true if a default value was specified
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:12
  def default_exists; end

  # @return [Symbol] the field name
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:9
  def name; end

  # @return [Boolean, nil] true if nil values are allowed
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:21
  def optional; end

  # Validate a value against the field's type definition.
  # Supports Ruby class types and Sorbet runtime types.
  #
  # @param value [Object] the value to validate
  # @raise [ArgTypeError] if the value doesn't match the expected type
  # @return [Object] the validated value
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:53
  def validate_type!(value); end

  private

  # pkg:gem/operandi#lib/operandi/settings/field.rb:115
  def define_methods; end

  # Check if the type is a plain Ruby class (not a Sorbet type)
  #
  # @return [Boolean]
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:77
  def plain_class_type?(type); end

  # Check if sorbet-runtime is available
  #
  # @return [Boolean]
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:72
  def sorbet_available?; end

  # Check if the type is a Sorbet runtime type
  #
  # @return [Boolean]
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:82
  def sorbet_type?(type); end

  # pkg:gem/operandi#lib/operandi/settings/field.rb:109
  def type_error_message(value); end

  # Validate value against Ruby class types
  #
  # @raise [Operandi::ArgTypeError]
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:103
  def validate_ruby_type!(value); end

  # Validate value against Sorbet runtime types
  # Note: Sorbet types only validate, they do not coerce values
  # Automatically coerces plain Ruby classes to Sorbet types when needed
  #
  # @raise [ArgTypeError] if the value doesn't match the expected type
  # @return [Object] the original value if valid
  #
  # pkg:gem/operandi#lib/operandi/settings/field.rb:93
  def validate_sorbet_type!(value); end
end

# pkg:gem/operandi#lib/operandi/settings/field.rb:64
Operandi::Settings::Field::FIELD_TYPE_TO_IVAR = T.let(T.unsafe(nil), Hash)

# pkg:gem/operandi#lib/operandi/settings/field.rb:130
Operandi::Settings::Output = Operandi::Settings::Field

# Stores configuration for a single service step.
# Created automatically when using the `step` DSL method.
#
# pkg:gem/operandi#lib/operandi/settings/step.rb:7
class Operandi::Settings::Step
  # Initialize a new step definition.
  #
  # @option opts
  # @option opts
  # @option opts
  # @param name [Symbol] the step name (must match a method)
  # @param opts [Hash] step options
  # @param service_class [Class] the service class this step belongs to
  # @raise [Error] if both :if and :unless are specified
  # @return [Step] a new instance of Step
  #
  # pkg:gem/operandi#lib/operandi/settings/step.rb:23
  def initialize(name, service_class, opts = T.unsafe(nil)); end

  # @return [Boolean, nil] true if step runs even after errors/warnings
  #
  # pkg:gem/operandi#lib/operandi/settings/step.rb:12
  def always; end

  # @return [Symbol] the step name (method to call)
  #
  # pkg:gem/operandi#lib/operandi/settings/step.rb:9
  def name; end

  # Execute the step on the given service instance.
  #
  # @param instance [Base] the service instance
  # @raise [Error] if the step method is not defined
  # @return [Boolean] true if the step was executed, false if skipped
  #
  # pkg:gem/operandi#lib/operandi/settings/step.rb:42
  def run(instance); end

  private

  # pkg:gem/operandi#lib/operandi/settings/step.rb:91
  def check_condition(condition, instance); end

  # pkg:gem/operandi#lib/operandi/settings/step.rb:58
  def execute_with_callbacks(instance); end

  # @return [Boolean]
  #
  # pkg:gem/operandi#lib/operandi/settings/step.rb:79
  def run?(instance); end
end

# Control flow exception for stop_immediately!
# Not an error - used to halt execution gracefully.
#
# pkg:gem/operandi#lib/operandi/exceptions.rb:24
class Operandi::StopExecution < ::StandardError; end

# @deprecated Use {Error} instead
#
# pkg:gem/operandi#lib/operandi/exceptions.rb:34
Operandi::TwoConditions = Operandi::Error

# Utility module providing helper methods for the Operandi library
#
# pkg:gem/operandi#lib/operandi/utils.rb:5
module Operandi::Utils
  private

  # Creates a deep copy of an object to prevent mutation of shared references.
  #
  # @example Deep duping a hash
  #   original = { a: { b: 1 } }
  #   copy = Utils.deep_dup(original)
  #   copy[:a][:b] = 2
  #   original[:a][:b] # => 1
  # @example Deep duping an array
  #   original = [[1, 2], [3, 4]]
  #   copy = Utils.deep_dup(original)
  #   copy[0] << 5
  #   original[0] # => [1, 2]
  # @param object [Object] the object to duplicate
  # @return [Object] a deep copy of the object
  #
  # pkg:gem/operandi#lib/operandi/utils.rb:25
  def deep_dup(object); end

  class << self
    # Creates a deep copy of an object to prevent mutation of shared references.
    #
    # @example Deep duping a hash
    #   original = { a: { b: 1 } }
    #   copy = Utils.deep_dup(original)
    #   copy[:a][:b] = 2
    #   original[:a][:b] # => 1
    # @example Deep duping an array
    #   original = [[1, 2], [3, 4]]
    #   copy = Utils.deep_dup(original)
    #   copy[0] << 5
    #   original[0] # => [1, 2]
    # @param object [Object] the object to duplicate
    # @return [Object] a deep copy of the object
    #
    # pkg:gem/operandi#lib/operandi/utils.rb:25
    def deep_dup(object); end
  end
end

# pkg:gem/operandi#lib/operandi/version.rb:4
Operandi::VERSION = T.let(T.unsafe(nil), String)
