# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `phlex-sorbet` gem.
# Please instead update this file by running `bin/tapioca gem phlex-sorbet`.


# pkg:gem/phlex-sorbet#lib/phlex/sorbet/errors.rb:4
module Phlex; end

# pkg:gem/phlex-sorbet#lib/phlex/sorbet/errors.rb:5
module Phlex::Sorbet
  mixes_in_class_methods ::Phlex::Sorbet::ClassMethods

  class << self
    # Hook called when Phlex::Sorbet is included in a component class.
    # Wires up class-level Props helpers and prepends an `initialize` that
    # builds a typed `Props` struct from incoming kwargs.
    #
    # pkg:gem/phlex-sorbet#lib/phlex/sorbet.rb:30
    sig { params(base: T.untyped).void }
    def included(base); end
  end
end

# Class methods added to components that include Phlex::Sorbet
#
# pkg:gem/phlex-sorbet#lib/phlex/sorbet/class_methods.rb:9
module Phlex::Sorbet::ClassMethods
  # Builds and validates a Props instance from incoming kwargs.
  # Uses sorbet-schema's HashSerializer so that nested T::Structs and
  # coercible primitive types (e.g. "1" -> 1) are supported.
  #
  # Returns nil if no Props class is defined and no kwargs were given.
  #
  # @raise [InvalidPropsError] if validation fails
  # @raise [PropsNotDefinedError] if kwargs are given but no Props class is defined
  #
  # pkg:gem/phlex-sorbet#lib/phlex/sorbet/class_methods.rb:40
  sig { params(kwargs: T.untyped).returns(T.nilable(::T::Struct)) }
  def build_props(**kwargs); end

  # Returns the Props class for this component, or nil if not defined.
  #
  # pkg:gem/phlex-sorbet#lib/phlex/sorbet/class_methods.rb:16
  sig { returns(T.nilable(T.class_of(T::Struct))) }
  def props_class; end

  private

  # Runs sorbet-schema deserialization for the given Props class and kwargs.
  #
  # @raise [InvalidPropsError]
  #
  # pkg:gem/phlex-sorbet#lib/phlex/sorbet/class_methods.rb:60
  sig do
    params(
      klass: T.class_of(T::Struct),
      kwargs: T::Hash[T.any(::String, ::Symbol), T.untyped]
    ).returns(::T::Struct)
  end
  def deserialize_props(klass, kwargs); end

  # Validates that the Props class is a T::Struct
  #
  # @raise [PropsNotDefinedError] if invalid
  #
  # pkg:gem/phlex-sorbet#lib/phlex/sorbet/class_methods.rb:74
  sig { params(klass: T.untyped).returns(T.class_of(T::Struct)) }
  def validate_props_class!(klass); end
end

# Base error class for all Phlex::Sorbet errors
#
# pkg:gem/phlex-sorbet#lib/phlex/sorbet/errors.rb:7
class Phlex::Sorbet::Error < ::StandardError; end

# Instance methods prepended into components that include Phlex::Sorbet.
# Wraps `initialize` to build a typed Props struct from incoming kwargs
# and exposes each prop as a method on the component instance.
#
# pkg:gem/phlex-sorbet#lib/phlex/sorbet/instance_methods.rb:11
module Phlex::Sorbet::InstanceMethods
  # Builds typed props, defines per-prop accessor methods, then calls
  # super so the Phlex base class can initialize as usual.
  #
  # @param kwargs [Hash] Arguments matching the Props T::Struct
  # @raise [InvalidPropsError] if validation fails
  #
  # pkg:gem/phlex-sorbet#lib/phlex/sorbet/instance_methods.rb:19
  def initialize(**kwargs, &_arg1); end

  # Accessor for typed props.
  #
  # pkg:gem/phlex-sorbet#lib/phlex/sorbet/instance_methods.rb:29
  sig { returns(T.nilable(::T::Struct)) }
  def props; end

  private

  # Define getter methods for each field in the Props struct.
  # Allows direct access like `user_id` instead of `props.user_id`.
  #
  # pkg:gem/phlex-sorbet#lib/phlex/sorbet/instance_methods.rb:40
  sig { void }
  def define_prop_accessors; end
end

# Raised when prop validation fails at instantiation time
#
# pkg:gem/phlex-sorbet#lib/phlex/sorbet/errors.rb:13
class Phlex::Sorbet::InvalidPropsError < ::Phlex::Sorbet::Error; end

# Raised when a component doesn't define a Props class or it's not a T::Struct
#
# pkg:gem/phlex-sorbet#lib/phlex/sorbet/errors.rb:10
class Phlex::Sorbet::PropsNotDefinedError < ::Phlex::Sorbet::Error; end

# Raised when sorbet-schema deserialization fails
#
# pkg:gem/phlex-sorbet#lib/phlex/sorbet/errors.rb:16
class Phlex::Sorbet::SerializationError < ::Phlex::Sorbet::Error; end

# pkg:gem/phlex-sorbet#lib/phlex/sorbet/version.rb:5
Phlex::Sorbet::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/phlex-sorbet#lib/tapioca/dsl/compilers/phlex_sorbet.rb:6
module Tapioca; end

# pkg:gem/phlex-sorbet#lib/tapioca/dsl/compilers/phlex_sorbet.rb:7
module Tapioca::Dsl; end

# pkg:gem/phlex-sorbet#lib/tapioca/dsl/compilers/phlex_sorbet.rb:8
module Tapioca::Dsl::Compilers; end

# Generates RBI files for Phlex::Sorbet components.
#
# This compiler generates:
# - Instance methods for direct prop access (user_id, notify, etc.)
# - A typed `initialize` signature derived from the component's `Props` struct
#
# pkg:gem/phlex-sorbet#lib/tapioca/dsl/compilers/phlex_sorbet.rb:14
class Tapioca::Dsl::Compilers::PhlexSorbet < ::Tapioca::Dsl::Compiler
  extend T::Generic

  ConstantType = type_member { { fixed: T.class_of(Phlex::Sorbet) } }

  # pkg:gem/phlex-sorbet#lib/tapioca/dsl/compilers/phlex_sorbet.rb:21
  sig { override.void }
  def decorate; end

  private

  # pkg:gem/phlex-sorbet#lib/tapioca/dsl/compilers/phlex_sorbet.rb:68
  sig { returns(T::Array[::RBI::TypedParam]) }
  def build_params_signature; end

  # pkg:gem/phlex-sorbet#lib/tapioca/dsl/compilers/phlex_sorbet.rb:59
  sig { params(klass: ::RBI::Scope).void }
  def generate_initialize_method(klass); end

  # pkg:gem/phlex-sorbet#lib/tapioca/dsl/compilers/phlex_sorbet.rb:45
  sig { params(klass: ::RBI::Scope).void }
  def generate_prop_accessors(klass); end

  # pkg:gem/phlex-sorbet#lib/tapioca/dsl/compilers/phlex_sorbet.rb:38
  sig { returns(T.nilable(T.class_of(T::Struct))) }
  def props_class; end

  class << self
    # pkg:gem/phlex-sorbet#lib/tapioca/dsl/compilers/phlex_sorbet.rb:29
    sig { override.returns(T::Enumerable[T::Module[T.anything]]) }
    def gather_constants; end
  end
end

class Tapioca::Error < ::StandardError; end
