# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sorbet-model-attributes` gem.
# Please instead update this file by running `bin/tapioca gem sorbet-model-attributes`.


# pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/version.rb:4
module SorbetModelAttributes; end

# pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes.rb:14
class SorbetModelAttributes::DeserializationError < ::SorbetModelAttributes::Error; end

# pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes.rb:13
class SorbetModelAttributes::Error < ::StandardError; end

# pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:5
module SorbetModelAttributes::ModelConcern
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::SorbetModelAttributes::ModelConcern::ClassMethods

  # pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:68
  def reload(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:127
  def _build_detailed_deserialization_error(column_name, schema, hash, original_error); end

  # pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:137
  def _collect_nested_field_errors(schema, hash, prefix = T.unsafe(nil)); end

  # pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:108
  def _serialize_sorbet_attributes; end

  # pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:194
  def _struct_type?(type); end

  # pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:169
  def _try_nested_errors(field, value, field_path); end

  # pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:89
  def _write_sorbet_hash(column_name, ivar, serializer, hash); end

  # pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:77
  def _write_sorbet_struct(column_name, ivar, serializer, struct); end

  module GeneratedClassMethods
    def _sorbet_attribute_definitions; end
    def _sorbet_attribute_definitions=(value); end
    def _sorbet_attribute_definitions?; end
  end

  module GeneratedInstanceMethods
    def _sorbet_attribute_definitions; end
    def _sorbet_attribute_definitions?; end
  end
end

# pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:14
module SorbetModelAttributes::ModelConcern::ClassMethods
  # pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:15
  def sorbet_attributes(column_name, struct_class, optional: T.unsafe(nil)); end

  private

  # pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:27
  def _define_sorbet_getter(column_name, serializer); end

  # pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/model_concern.rb:48
  def _define_sorbet_setter(column_name, struct_class, serializer); end
end

# pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/railtie.rb:5
class SorbetModelAttributes::Railtie < ::Rails::Railtie; end

# pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes.rb:15
class SorbetModelAttributes::SerializationError < ::SorbetModelAttributes::Error; end

# pkg:gem/sorbet-model-attributes#lib/sorbet-model-attributes/version.rb:5
SorbetModelAttributes::VERSION = T.let(T.unsafe(nil), String)
