# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sorbet-schema` gem.
# Please instead update this file by running `bin/tapioca gem sorbet-schema`.


# typed: strict

# We don't want a dependency on ActiveSupport.
# This is a simplified version of ActiveSupport's Key Hash extension
# https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/hash/keys.rb
#
# pkg:gem/sorbet-schema#lib/sorbet-schema/hash_transformer.rb:6
class HashTransformer
  class << self
    # pkg:gem/sorbet-schema#lib/sorbet-schema/hash_transformer.rb:18
    sig { params(hash: T::Hash[T.untyped, T.untyped]).returns(T::Hash[T.untyped, T.untyped]) }
    def serialize_values(hash); end

    # pkg:gem/sorbet-schema#lib/sorbet-schema/hash_transformer.rb:11
    sig { params(hash: T::Hash[T.untyped, T.untyped]).returns(T::Hash[::Symbol, T.untyped]) }
    def symbolize_keys(hash); end
  end
end

# pkg:gem/sorbet-schema#lib/sorbet-schema/serialize_value.rb:3
class SerializeValue
  class << self
    # pkg:gem/sorbet-schema#lib/sorbet-schema/serialize_value.rb:7
    sig { params(value: T.untyped).returns(T.untyped) }
    def serialize(value); end
  end
end

# pkg:gem/sorbet-schema#lib/sorbet-schema/t/struct.rb:4
class T::Struct < ::T::InexactStruct
  # pkg:gem/sorbet-schema#lib/sorbet-schema/t/struct.rb:26
  sig do
    params(
      serializer_type: Symbol,
      options: T::Hash[Symbol, T.untyped]
    ).returns(Typed::Result[T.untyped, Typed::SerializeError])
  end
  def serialize_to(serializer_type, options: {}); end

  class << self
    # pkg:gem/sorbet-schema#lib/sorbet-schema/t/struct.rb:21
    sig do
      params(
        serializer_type: Symbol,
        source: T.untyped,
        options: T::Hash[Symbol, T.untyped]
      ).returns(Typed::Result[T.attached_class, Typed::DeserializeError])
    end
    def deserialize_from(serializer_type, source, options: {}); end

    # pkg:gem/sorbet-schema#lib/sorbet-schema/t/struct.rb:6
    sig { overridable.returns(Typed::Schema) }
    def schema; end

    # pkg:gem/sorbet-schema#lib/sorbet-schema/t/struct.rb:10
    sig { params(type: Symbol, options: T::Hash[Symbol, T.untyped]).returns(Typed::Serializer[T.untyped, T.untyped]) }
    def serializer(type, options: {}); end
  end
end

# Sorbet-aware namespace to super-charge your projects
#
# pkg:gem/sorbet-schema#lib/sorbet-schema.rb:32
module Typed; end

# pkg:gem/sorbet-schema#lib/typed/coercion.rb:4
module Typed::Coercion
  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion.rb:13
    sig do
      params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[T.untyped, ::Typed::Coercion::CoercionError])
    end
    def coerce(type:, value:); end

    # pkg:gem/sorbet-schema#lib/typed/coercion.rb:8
    sig { params(coercer: T.class_of(Typed::Coercion::Coercer)).void }
    def register_coercer(coercer); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/boolean_coercer.rb:5
class Typed::Coercion::BooleanCoercer < ::Typed::Coercion::Coercer
  extend T::Generic

  Target = type_member { { fixed: T::Boolean } }

  # pkg:gem/sorbet-schema#lib/typed/coercion/boolean_coercer.rb:16
  sig do
    override
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/boolean_coercer.rb:11
    sig { override.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/coercer.rb:5
class Typed::Coercion::Coercer
  extend T::Generic

  abstract!

  Target = type_member(:out)

  # pkg:gem/sorbet-schema#lib/typed/coercion/coercer.rb:18
  sig do
    abstract
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/coercer.rb:14
    sig { abstract.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/coercer_registry.rb:7
class Typed::Coercion::CoercerRegistry
  include ::Singleton::SingletonInstanceMethods
  include ::Singleton
  extend ::Singleton::SingletonClassMethods

  # pkg:gem/sorbet-schema#lib/typed/coercion/coercer_registry.rb:32
  sig { void }
  def initialize; end

  # pkg:gem/sorbet-schema#lib/typed/coercion/coercer_registry.rb:37
  sig { params(coercer: T.class_of(Typed::Coercion::Coercer)).void }
  def register(coercer); end

  # pkg:gem/sorbet-schema#lib/typed/coercion/coercer_registry.rb:42
  sig { void }
  def reset!; end

  # pkg:gem/sorbet-schema#lib/typed/coercion/coercer_registry.rb:47
  sig { params(type: ::T::Types::Base).returns(T.nilable(T.class_of(Typed::Coercion::Coercer))) }
  def select_coercer_by(type:); end

  class << self
    private

    # pkg:gem/sorbet-schema#lib/typed/coercion/coercer_registry.rb:10
    def allocate; end

    # pkg:gem/sorbet-schema#lib/typed/coercion/coercer_registry.rb:10
    def new(*_arg0); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/coercer_registry.rb:14
Typed::Coercion::CoercerRegistry::DEFAULT_COERCERS = T.let(T.unsafe(nil), Array)

# pkg:gem/sorbet-schema#lib/typed/coercion/coercer_registry.rb:12
Typed::Coercion::CoercerRegistry::Registry = T.type_alias { T::Array[T.class_of(Typed::Coercion::Coercer)] }

# pkg:gem/sorbet-schema#lib/typed/coercion/coercion_error.rb:5
class Typed::Coercion::CoercionError < ::StandardError; end

# pkg:gem/sorbet-schema#lib/typed/coercion/coercion_not_supported_error.rb:5
class Typed::Coercion::CoercionNotSupportedError < ::Typed::Coercion::CoercionError
  # pkg:gem/sorbet-schema#lib/typed/coercion/coercion_not_supported_error.rb:9
  sig { params(type: ::T::Types::Base).void }
  def initialize(type:); end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/date_coercer.rb:7
class Typed::Coercion::DateCoercer < ::Typed::Coercion::Coercer
  extend T::Generic

  Target = type_member { { fixed: Date } }

  # pkg:gem/sorbet-schema#lib/typed/coercion/date_coercer.rb:18
  sig do
    override
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/date_coercer.rb:13
    sig { override.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/date_time_coercer.rb:7
class Typed::Coercion::DateTimeCoercer < ::Typed::Coercion::Coercer
  extend T::Generic

  Target = type_member { { fixed: DateTime } }

  # pkg:gem/sorbet-schema#lib/typed/coercion/date_time_coercer.rb:18
  sig do
    override
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/date_time_coercer.rb:13
    sig { override.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/enum_coercer.rb:5
class Typed::Coercion::EnumCoercer < ::Typed::Coercion::Coercer
  extend T::Generic

  Target = type_member { { fixed: T::Enum } }

  # pkg:gem/sorbet-schema#lib/typed/coercion/enum_coercer.rb:18
  sig do
    override
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/enum_coercer.rb:11
    sig { override.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/float_coercer.rb:5
class Typed::Coercion::FloatCoercer < ::Typed::Coercion::Coercer
  extend T::Generic

  Target = type_member { { fixed: Float } }

  # pkg:gem/sorbet-schema#lib/typed/coercion/float_coercer.rb:16
  sig do
    override
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/float_coercer.rb:11
    sig { override.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/integer_coercer.rb:5
class Typed::Coercion::IntegerCoercer < ::Typed::Coercion::Coercer
  extend T::Generic

  Target = type_member { { fixed: Integer } }

  # pkg:gem/sorbet-schema#lib/typed/coercion/integer_coercer.rb:16
  sig do
    override
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/integer_coercer.rb:11
    sig { override.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/string_coercer.rb:5
class Typed::Coercion::StringCoercer < ::Typed::Coercion::Coercer
  extend T::Generic

  Target = type_member { { fixed: String } }

  # pkg:gem/sorbet-schema#lib/typed/coercion/string_coercer.rb:16
  sig do
    override
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/string_coercer.rb:11
    sig { override.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/struct_coercer.rb:5
class Typed::Coercion::StructCoercer < ::Typed::Coercion::Coercer
  extend T::Generic

  Target = type_member { { fixed: T::Struct } }

  # pkg:gem/sorbet-schema#lib/typed/coercion/struct_coercer.rb:18
  sig do
    override
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/struct_coercer.rb:11
    sig { override.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/symbol_coercer.rb:5
class Typed::Coercion::SymbolCoercer < ::Typed::Coercion::Coercer
  extend T::Generic

  Target = type_member { { fixed: Symbol } }

  # pkg:gem/sorbet-schema#lib/typed/coercion/symbol_coercer.rb:16
  sig do
    override
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/symbol_coercer.rb:11
    sig { override.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/typed_array_coercer.rb:5
class Typed::Coercion::TypedArrayCoercer < ::Typed::Coercion::Coercer
  extend T::Generic

  Target = type_member { { fixed: T::Array[T.untyped] } }

  # pkg:gem/sorbet-schema#lib/typed/coercion/typed_array_coercer.rb:16
  sig do
    override
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/typed_array_coercer.rb:11
    sig { override.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/coercion/typed_hash_coercer.rb:5
class Typed::Coercion::TypedHashCoercer < ::Typed::Coercion::Coercer
  extend T::Generic

  Target = type_member { { fixed: T::Hash[T.untyped, T.untyped] } }

  # pkg:gem/sorbet-schema#lib/typed/coercion/typed_hash_coercer.rb:16
  sig do
    override
      .params(
        type: ::T::Types::Base,
        value: T.untyped
      ).returns(Typed::Result[Target, ::Typed::Coercion::CoercionError])
  end
  def coerce(type:, value:); end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/coercion/typed_hash_coercer.rb:11
    sig { override.params(type: ::T::Types::Base).returns(T::Boolean) }
    def used_for_type?(type); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/deserialize_error.rb:4
class Typed::DeserializeError < ::Typed::SerializationError
  # pkg:gem/sorbet-schema#lib/typed/deserialize_error.rb:8
  sig { returns({error: ::String}) }
  def to_h; end

  # pkg:gem/sorbet-schema#lib/typed/deserialize_error.rb:13
  sig { params(_options: T::Hash[T.untyped, T.untyped]).returns(::String) }
  def to_json(_options = T.unsafe(nil)); end
end

# pkg:gem/sorbet-schema#lib/typed/field.rb:4
class Typed::Field
  # pkg:gem/sorbet-schema#lib/typed/field.rb:33
  sig do
    params(
      name: ::Symbol,
      type: T.any(::T::Types::Base, T::Class[T.anything]),
      optional: T::Boolean,
      default: T.untyped,
      inline_serializer: T.nilable(T.proc.params(arg0: T.untyped).returns(T.untyped))
    ).void
  end
  def initialize(name:, type:, optional: T.unsafe(nil), default: T.unsafe(nil), inline_serializer: T.unsafe(nil)); end

  # pkg:gem/sorbet-schema#lib/typed/field.rb:61
  sig { params(other: ::Typed::Field).returns(T.nilable(T::Boolean)) }
  def ==(other); end

  # pkg:gem/sorbet-schema#lib/typed/field.rb:16
  sig { returns(T.untyped) }
  def default; end

  # pkg:gem/sorbet-schema#lib/typed/field.rb:22
  sig { returns(T.nilable(T.proc.params(arg0: T.untyped).returns(T.untyped))) }
  def inline_serializer; end

  # pkg:gem/sorbet-schema#lib/typed/field.rb:10
  sig { returns(::Symbol) }
  def name; end

  # pkg:gem/sorbet-schema#lib/typed/field.rb:75
  sig { returns(T::Boolean) }
  def optional?; end

  # pkg:gem/sorbet-schema#lib/typed/field.rb:19
  sig { returns(T::Boolean) }
  def required; end

  # pkg:gem/sorbet-schema#lib/typed/field.rb:70
  sig { returns(T::Boolean) }
  def required?; end

  # pkg:gem/sorbet-schema#lib/typed/field.rb:80
  sig { params(value: T.untyped).returns(T.untyped) }
  def serialize(value); end

  # pkg:gem/sorbet-schema#lib/typed/field.rb:13
  sig { returns(::T::Types::Base) }
  def type; end

  # pkg:gem/sorbet-schema#lib/typed/field.rb:89
  sig do
    params(
      value: T.untyped
    ).returns(Typed::Result[::Typed::Validations::ValidatedValue, ::Typed::Validations::ValidationError])
  end
  def validate(value); end

  # pkg:gem/sorbet-schema#lib/typed/field.rb:94
  sig { params(value: T.untyped).returns(T::Boolean) }
  def works_with?(value); end
end

# pkg:gem/sorbet-schema#lib/typed/field.rb:7
Typed::Field::InlineSerializer = T.type_alias { T.proc.params(arg0: T.untyped).returns(T.untyped) }

# pkg:gem/sorbet-schema#lib/typed/hash_serializer.rb:4
class Typed::HashSerializer < ::Typed::Serializer
  extend T::Generic

  Input = type_member { { fixed: T::Hash[T.any(::String, ::Symbol), T.untyped] } }
  Output = type_member { { fixed: T::Hash[::Symbol, T.untyped] } }

  # pkg:gem/sorbet-schema#lib/typed/hash_serializer.rb:13
  sig { params(schema: ::Typed::Schema, should_serialize_values: T::Boolean).void }
  def initialize(schema:, should_serialize_values: T.unsafe(nil)); end

  # pkg:gem/sorbet-schema#lib/typed/hash_serializer.rb:20
  sig { override.params(source: Input).returns(Typed::Result[::T::Struct, ::Typed::DeserializeError]) }
  def deserialize(source); end

  # pkg:gem/sorbet-schema#lib/typed/hash_serializer.rb:25
  sig { override.params(struct: ::T::Struct).returns(Typed::Result[Output, ::Typed::SerializeError]) }
  def serialize(struct); end

  # pkg:gem/sorbet-schema#lib/typed/hash_serializer.rb:10
  sig { returns(T::Boolean) }
  def should_serialize_values; end
end

# pkg:gem/sorbet-schema#lib/typed/hash_serializer.rb:5
Typed::HashSerializer::InputHash = T.type_alias { T::Hash[T.any(::String, ::Symbol), T.untyped] }

# pkg:gem/sorbet-schema#lib/typed/json_serializer.rb:6
class Typed::JSONSerializer < ::Typed::Serializer
  extend T::Generic

  Input = type_member { { fixed: String } }
  Output = type_member { { fixed: String } }

  # pkg:gem/sorbet-schema#lib/typed/json_serializer.rb:11
  sig { override.params(source: Input).returns(Typed::Result[::T::Struct, ::Typed::DeserializeError]) }
  def deserialize(source); end

  # pkg:gem/sorbet-schema#lib/typed/json_serializer.rb:24
  sig { override.params(struct: ::T::Struct).returns(Typed::Result[Output, ::Typed::SerializeError]) }
  def serialize(struct); end
end

# pkg:gem/sorbet-schema#lib/typed/parse_error.rb:4
class Typed::ParseError < ::Typed::DeserializeError
  # pkg:gem/sorbet-schema#lib/typed/parse_error.rb:8
  sig { params(format: ::Symbol).void }
  def initialize(format:); end
end

# pkg:gem/sorbet-schema#lib/typed/schema.rb:4
class Typed::Schema < ::T::Struct
  include ::Comparable

  const :fields, T::Array[::Typed::Field], default: T.unsafe(nil)
  const :target, T.class_of(T::Struct)

  # pkg:gem/sorbet-schema#lib/typed/schema.rb:32
  sig do
    params(
      field_name: ::Symbol,
      serializer: T.proc.params(arg0: T.untyped).returns(T.untyped)
    ).returns(::Typed::Schema)
  end
  def add_serializer(field_name, serializer); end

  # pkg:gem/sorbet-schema#lib/typed/schema.rb:22
  sig do
    params(
      hash: T::Hash[T.any(::String, ::Symbol), T.untyped]
    ).returns(Typed::Result[::T::Struct, ::Typed::DeserializeError])
  end
  def from_hash(hash); end

  # pkg:gem/sorbet-schema#lib/typed/schema.rb:27
  sig { params(json: ::String).returns(Typed::Result[::T::Struct, ::Typed::DeserializeError]) }
  def from_json(json); end

  private

  # pkg:gem/sorbet-schema#lib/typed/schema.rb:48
  sig { returns(Typed::HashSerializer) }
  def hash_serializer; end

  # pkg:gem/sorbet-schema#lib/typed/schema.rb:54
  sig { returns(Typed::JSONSerializer) }
  def json_serializer; end

  class << self
    # pkg:gem/sorbet-schema#lib/typed/schema.rb:12
    sig { params(struct: T.class_of(T::Struct)).returns(::Typed::Schema) }
    def from_struct(struct); end
  end
end

# pkg:gem/sorbet-schema#lib/typed/serialization_error.rb:4
class Typed::SerializationError < ::StandardError
  # pkg:gem/sorbet-schema#lib/typed/serialization_error.rb:8
  sig { returns({error: ::String}) }
  def to_h; end

  # pkg:gem/sorbet-schema#lib/typed/serialization_error.rb:13
  sig { params(_options: T::Hash[T.untyped, T.untyped]).returns(::String) }
  def to_json(_options = T.unsafe(nil)); end
end

# pkg:gem/sorbet-schema#lib/typed/serialize_error.rb:4
class Typed::SerializeError < ::Typed::SerializationError; end

# pkg:gem/sorbet-schema#lib/typed/serializer.rb:4
class Typed::Serializer
  extend T::Generic

  abstract!

  Input = type_member
  Output = type_member

  # pkg:gem/sorbet-schema#lib/typed/serializer.rb:22
  sig { params(schema: ::Typed::Schema).void }
  def initialize(schema:); end

  # pkg:gem/sorbet-schema#lib/typed/serializer.rb:19
  sig { returns(T::Hash[::T::Types::Base, T.untyped]) }
  def coercer_cache; end

  # pkg:gem/sorbet-schema#lib/typed/serializer.rb:28
  sig { abstract.params(source: Input).returns(Typed::Result[::T::Struct, ::Typed::DeserializeError]) }
  def deserialize(source); end

  # pkg:gem/sorbet-schema#lib/typed/serializer.rb:16
  sig { returns(::Typed::Schema) }
  def schema; end

  # pkg:gem/sorbet-schema#lib/typed/serializer.rb:32
  sig { abstract.params(struct: ::T::Struct).returns(Typed::Result[Output, ::Typed::SerializeError]) }
  def serialize(struct); end

  private

  # pkg:gem/sorbet-schema#lib/typed/serializer.rb:38
  sig do
    params(
      creation_params: T::Hash[::Symbol, T.untyped]
    ).returns(Typed::Result[::T::Struct, ::Typed::DeserializeError])
  end
  def deserialize_from_creation_params(creation_params); end

  # pkg:gem/sorbet-schema#lib/typed/serializer.rb:101
  sig { params(type: ::T::Types::Base).returns(T.untyped) }
  def fetch_coercer(type); end

  # pkg:gem/sorbet-schema#lib/typed/serializer.rb:90
  sig { params(struct: ::T::Struct, should_serialize_values: T::Boolean).returns(T::Hash[::Symbol, T.untyped]) }
  def serialize_from_struct(struct:, should_serialize_values: T.unsafe(nil)); end
end

# pkg:gem/sorbet-schema#lib/typed/serializer.rb:13
Typed::Serializer::DeserializeResult = T.type_alias { Typed::Result[::T::Struct, ::Typed::DeserializeError] }

# pkg:gem/sorbet-schema#lib/typed/serializer.rb:12
Typed::Serializer::Params = T.type_alias { T::Hash[::Symbol, T.untyped] }

# pkg:gem/sorbet-schema#lib/typed/validations.rb:4
module Typed::Validations; end

# pkg:gem/sorbet-schema#lib/typed/validations/field_type_validator.rb:5
class Typed::Validations::FieldTypeValidator
  include ::Typed::Validations::FieldValidator

  # pkg:gem/sorbet-schema#lib/typed/validations/field_type_validator.rb:11
  sig do
    override
      .params(
        field: ::Typed::Field,
        value: T.untyped
      ).returns(Typed::Result[::Typed::Validations::ValidatedValue, ::Typed::Validations::ValidationError])
  end
  def validate(field:, value:); end
end

# pkg:gem/sorbet-schema#lib/typed/validations/field_validator.rb:5
module Typed::Validations::FieldValidator
  interface!

  # pkg:gem/sorbet-schema#lib/typed/validations/field_validator.rb:11
  sig do
    abstract
      .params(
        field: ::Typed::Field,
        value: T.untyped
      ).returns(Typed::Result[::Typed::Validations::ValidatedValue, ::Typed::Validations::ValidationError])
  end
  def validate(field:, value:); end
end

# pkg:gem/sorbet-schema#lib/typed/validations/multiple_validation_error.rb:5
class Typed::Validations::MultipleValidationError < ::Typed::Validations::ValidationError
  # pkg:gem/sorbet-schema#lib/typed/validations/multiple_validation_error.rb:9
  sig { params(errors: T::Array[::Typed::Validations::ValidationError]).void }
  def initialize(errors:); end
end

# pkg:gem/sorbet-schema#lib/typed/validations/required_field_error.rb:5
class Typed::Validations::RequiredFieldError < ::Typed::Validations::ValidationError
  # pkg:gem/sorbet-schema#lib/typed/validations/required_field_error.rb:9
  sig { params(field_name: ::Symbol).void }
  def initialize(field_name:); end
end

# pkg:gem/sorbet-schema#lib/typed/validations/type_mismatch_error.rb:5
class Typed::Validations::TypeMismatchError < ::Typed::Validations::ValidationError
  # pkg:gem/sorbet-schema#lib/typed/validations/type_mismatch_error.rb:9
  sig { params(field_name: ::Symbol, field_type: ::T::Types::Base, given_type: T::Class[T.anything]).void }
  def initialize(field_name:, field_type:, given_type:); end
end

# pkg:gem/sorbet-schema#lib/typed/validations.rb:6
Typed::Validations::ValidatedParams = T.type_alias { T::Hash[::Symbol, T.untyped] }

# pkg:gem/sorbet-schema#lib/typed/validations/validated_value.rb:5
class Typed::Validations::ValidatedValue < ::T::Struct
  include ::Comparable

  const :name, ::Symbol
  const :value, T.untyped
end

# pkg:gem/sorbet-schema#lib/typed/validations/validation_error.rb:5
class Typed::Validations::ValidationError < ::Typed::DeserializeError; end

# pkg:gem/sorbet-schema#lib/typed/validations.rb:5
Typed::Validations::ValidationResult = T.type_alias { Typed::Result[::Typed::Validations::ValidatedValue, ::Typed::Validations::ValidationError] }

# pkg:gem/sorbet-schema#lib/typed/validations/validation_results.rb:5
class Typed::Validations::ValidationResults < ::T::Struct
  const :results, T::Array[Typed::Result[::Typed::Validations::ValidatedValue, ::Typed::Validations::ValidationError]]

  # pkg:gem/sorbet-schema#lib/typed/validations/validation_results.rb:11
  sig { returns(Typed::Result[T::Hash[::Symbol, T.untyped], ::Typed::Validations::ValidationError]) }
  def combine; end
end

# pkg:gem/sorbet-schema#lib/sorbet-schema.rb:33
Typed::Value = T.type_alias { T.untyped }
