# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sorbet-model-enum` gem.
# Please instead update this file by running `bin/tapioca gem sorbet-model-enum`.


# typed: true
# frozen_string_literal: true

# pkg:gem/sorbet-model-enum#lib/sorbet-model-enum/version.rb:4
module SorbetModelEnum; end

# pkg:gem/sorbet-model-enum#lib/sorbet-model-enum.rb:12
class SorbetModelEnum::Error < ::StandardError; end

# pkg:gem/sorbet-model-enum#lib/sorbet-model-enum/model_concern.rb:5
module SorbetModelEnum::ModelConcern
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::SorbetModelEnum::ModelConcern::ClassMethods

  module GeneratedClassMethods
    def _sorbet_enum_definitions; end
    def _sorbet_enum_definitions=(value); end
    def _sorbet_enum_definitions?; end
  end

  module GeneratedInstanceMethods
    def _sorbet_enum_definitions; end
    def _sorbet_enum_definitions?; end
  end
end

# pkg:gem/sorbet-model-enum#lib/sorbet-model-enum/model_concern.rb:12
module SorbetModelEnum::ModelConcern::ClassMethods
  # pkg:gem/sorbet-model-enum#lib/sorbet-model-enum/model_concern.rb:13
  sig { params(attr_name: T.any(Symbol, String), enum_class: T.class_of(T::Enum), options: T.untyped).void }
  def sorbet_enum(attr_name, enum_class, **options); end

  private

  # pkg:gem/sorbet-model-enum#lib/sorbet-model-enum/model_concern.rb:42
  def _build_enum_mapping(enum_class); end

  # pkg:gem/sorbet-model-enum#lib/sorbet-model-enum/model_concern.rb:77
  def _define_sorbet_array_enum_getter(attr_name, enum_class); end

  # pkg:gem/sorbet-model-enum#lib/sorbet-model-enum/model_concern.rb:86
  def _define_sorbet_array_enum_setter(attr_name, _enum_class); end

  # pkg:gem/sorbet-model-enum#lib/sorbet-model-enum/model_concern.rb:55
  def _define_sorbet_enum_getter(attr_name, enum_class); end

  # pkg:gem/sorbet-model-enum#lib/sorbet-model-enum/model_concern.rb:65
  def _define_sorbet_enum_setter(attr_name); end
end

# pkg:gem/sorbet-model-enum#lib/sorbet-model-enum/railtie.rb:5
class SorbetModelEnum::Railtie < ::Rails::Railtie; end

# pkg:gem/sorbet-model-enum#lib/sorbet-model-enum/version.rb:5
SorbetModelEnum::VERSION = T.let(T.unsafe(nil), String)
