# typed: strict
# frozen_string_literal: true

return unless defined?(Tapioca::Dsl::Compiler) && defined?(ActiveRecord::Base)

module Tapioca
  module Compilers
    # Generates RBI signatures for `self.` (singleton) methods that are
    # explicitly defined on `ActiveRecord::Base` subclasses, so they can be
    # called on relations (e.g. `Ticket.where(...).duplicates`).
    #
    # The methods are emitted on each model's `CommonRelationMethods` module,
    # which is included by `PrivateRelation`, `PrivateAssociationRelation`,
    # and `PrivateCollectionProxy` in the existing Tapioca-generated RBI.
    #
    # Methods generated by Rails (scopes, attribute methods, etc.) are
    # filtered out by limiting candidates to those whose `source_location`
    # lives under the application's `app/` directory.
    class ActiveRecordClassMethods < Tapioca::Dsl::Compiler
      ConstantType = type_member { { fixed: T.class_of(::ActiveRecord::Base) } }

      COMMON_RELATION_METHODS_MODULE_NAME = "CommonRelationMethods"

      APP_PATH_PREFIX = T.let(
        (defined?(Rails) && Rails.respond_to?(:root) && Rails.root ? Rails.root.join("app").to_s : nil),
        T.nilable(String),
      )

      class << self
        sig { override.returns(T::Enumerable[T::Module[T.anything]]) }
        def gather_constants
          descendants_of(::ActiveRecord::Base).reject do |klass|
            klass.abstract_class? || klass.name.nil?
          end
        end
      end

      sig { override.void }
      def decorate
        method_names = explicit_class_method_names
        return if method_names.empty?

        root.create_path(constant) do |model|
          common_relation_methods = model.create_module(COMMON_RELATION_METHODS_MODULE_NAME)

          method_names.each do |method_name|
            method_def = constant.method(method_name)
            create_method_from_def(common_relation_methods, method_def)
          end
        end
      end

      private

      sig { returns(T::Array[Symbol]) }
      def explicit_class_method_names
        prefix = APP_PATH_PREFIX
        return [] unless prefix

        scope_names = scope_method_names
        ar_base_methods = ::ActiveRecord::Base.methods

        method_names = constant.singleton_methods(false).select do |name|
          next false if scope_names.include?(name)
          next false if ar_base_methods.include?(name)

          method = begin
            constant.method(name)
          rescue NameError
            nil
          end

          next false unless method

          source_file = method.source_location&.first

          unless source_file&.start_with?(prefix)
            sig = T::Utils.signature_for_method(method)
            source_file = sig.method.source_location&.first if sig
          end

          source_file&.start_with?(prefix)
        end

        method_names.sort
      end

      sig { returns(T::Array[Symbol]) }
      def scope_method_names
        scope_methods = []
        klass = T.let(constant, T.class_of(::ActiveRecord::Base))

        until klass == ::ActiveRecord::Base
          scope_methods.concat(klass.send(:generated_relation_methods).instance_methods(false))

          superclass = klass.superclass
          break unless superclass.is_a?(Class) && superclass <= ::ActiveRecord::Base

          klass = superclass
        end

        scope_methods.uniq
      end
    end
  end
end
