# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Components::Card`.
# Please instead update this file by running `bin/tapioca dsl Components::Card`.


class Components::Card
  sig { params(bordered: T::Boolean).void }
  def initialize(bordered: T.unsafe(nil)); end

  sig { returns(T::Boolean) }
  def bordered; end

  class << self
    sig { params(bordered: T::Boolean).returns(T.attached_class) }
    def new(bordered: T.unsafe(nil)); end
  end
end
