# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Views::Dashboard::Index`.
# Please instead update this file by running `bin/tapioca dsl Views::Dashboard::Index`.


class Views::Dashboard::Index
  sig { params(title: ::String).void }
  def initialize(title:); end

  sig { returns(Views::Dashboard::Index::Props) }
  def props; end

  class << self
    sig { params(title: ::String).returns(T.attached_class) }
    def new(title:); end
  end
end
